// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVl7ehKH5_OegUi3yxJ8UqW7lWa7Y-Pg',
    appId: '1:65314358210:web:d61822183a04e504dd4c5b',
    messagingSenderId: '65314358210',
    projectId: 'komkowvadim-motes',
    authDomain: 'komkowvadim-motes.firebaseapp.com',
    storageBucket: 'komkowvadim-motes.appspot.com',
    measurementId: 'G-ECDWSGPL68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppZGJbAKB9ctRVsGX3ujFV9TYXO6RTLQ',
    appId: '1:65314358210:android:3f962358c37a92b5dd4c5b',
    messagingSenderId: '65314358210',
    projectId: 'komkowvadim-motes',
    storageBucket: 'komkowvadim-motes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcm9cdVV5ROQ1JGvOMzSXawh289ExLwo8',
    appId: '1:65314358210:ios:0b82ef6b0d79682edd4c5b',
    messagingSenderId: '65314358210',
    projectId: 'komkowvadim-motes',
    storageBucket: 'komkowvadim-motes.appspot.com',
    iosClientId: '65314358210-ea23u5ab3o8oga397en3qf4hoqionbbi.apps.googleusercontent.com',
    iosBundleId: 'comkomkov2000.vk.notes',
  );
}
